-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alumno_representante
(
    relacion_id integer NOT NULL,
    alumno_id integer NOT NULL,
    representantes_id integer NOT NULL,
    parentesco_id integer NOT NULL,
    es_principal smallint,
    status integer NOT NULL,
    CONSTRAINT alumno_representante_pkey PRIMARY KEY (relacion_id),
    CONSTRAINT uq_alumno_representante_parentesco UNIQUE (parentesco_id)
);

CREATE TABLE IF NOT EXISTS public.alumno_vacuna
(
    id_alumno_vacuna integer NOT NULL,
    alumno_id integer NOT NULL,
    vacuna_id integer NOT NULL,
    dosis_aplicada integer,
    fecha_aplicacion date,
    proxima_dosis date,
    lote character varying(50) COLLATE pg_catalog."default",
    observacion text COLLATE pg_catalog."default",
    activo integer,
    medical_id integer,
    CONSTRAINT alumno_vacuna_pkey PRIMARY KEY (id_alumno_vacuna)
);

CREATE TABLE IF NOT EXISTS public.alumnos
(
    id_alumnos integer NOT NULL,
    id_direccion integer NOT NULL,
    estatus integer NOT NULL,
    actividad_extra character varying(100) COLLATE pg_catalog."default" NOT NULL,
    talla_camisa character varying(100) COLLATE pg_catalog."default" NOT NULL,
    talla_pantalon character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alumnos_pkey PRIMARY KEY (id_alumnos)
);

CREATE TABLE IF NOT EXISTS public.alumnos_atencion_medica
(
    atencion_id integer NOT NULL,
    alumno_id integer NOT NULL,
    fecha_atencion date NOT NULL,
    motivo character varying(100) COLLATE pg_catalog."default",
    tratamiento text COLLATE pg_catalog."default",
    medico_responsable character varying(100) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    activo integer,
    medical_id integer,
    CONSTRAINT alumnos_atencion_medica_pkey PRIMARY KEY (atencion_id)
);

CREATE TABLE IF NOT EXISTS public.auditoria_notas
(
    id_auditoria integer NOT NULL,
    usuario_id integer NOT NULL,
    accion smallint NOT NULL,
    tipo_nota smallint NOT NULL,
    registro_id integer NOT NULL,
    valor_anterior text COLLATE pg_catalog."default",
    valor_nuevo text COLLATE pg_catalog."default",
    alumno_id integer,
    proyecto_id integer,
    materia_id integer,
    fecha timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auditoria_notas_pkey PRIMARY KEY (id_auditoria)
);

CREATE TABLE IF NOT EXISTS public.boletines_generados
(
    id_boletin integer NOT NULL,
    alumno_id integer NOT NULL,
    grado_id bigint NOT NULL,
    seccion_id bigint NOT NULL,
    periodo_id integer NOT NULL,
    momento smallint,
    proyecto_id integer,
    generado_por integer NOT NULL,
    fecha_generacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    archivo_pdf character varying(255) COLLATE pg_catalog."default",
    enviado_por_correo boolean DEFAULT false,
    fecha_envio timestamp with time zone,
    CONSTRAINT boletines_generados_pkey PRIMARY KEY (id_boletin)
);

CREATE TABLE IF NOT EXISTS public.cierres_momentos
(
    id_cierre integer NOT NULL,
    grado_id bigint NOT NULL,
    seccion_id bigint NOT NULL,
    periodo_id integer NOT NULL,
    momento smallint NOT NULL,
    cerrado_por integer NOT NULL,
    fecha_cierre timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    es_forzoso boolean DEFAULT false,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT cierres_momentos_pkey PRIMARY KEY (id_cierre),
    CONSTRAINT uq_cierre_unico UNIQUE (grado_id, seccion_id, periodo_id, momento)
);

CREATE TABLE IF NOT EXISTS public.ciudad
(
    id integer NOT NULL,
    descripcion character varying(250) COLLATE pg_catalog."default",
    estado_id integer,
    CONSTRAINT ciudad_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.configuracion_regla_calculo
(
    id_regla integer NOT NULL,
    materia_id integer,
    tipo_regla smallint DEFAULT 1,
    configuracion jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT configuracion_regla_calculo_pkey PRIMARY KEY (id_regla)
);

CREATE TABLE IF NOT EXISTS public.contacto_emergencia
(
    contacto_id integer NOT NULL,
    alumno_id integer NOT NULL,
    nombre_completo character varying(100) COLLATE pg_catalog."default",
    parentesco_id integer,
    telefono character varying(20) COLLATE pg_catalog."default",
    telefono_alternativo character varying(20) COLLATE pg_catalog."default",
    correo_electronico character varying(100) COLLATE pg_catalog."default",
    direccion character varying(100) COLLATE pg_catalog."default",
    activo integer,
    CONSTRAINT contacto_emergencia_pkey PRIMARY KEY (contacto_id)
);

CREATE TABLE IF NOT EXISTS public.direccion
(
    id_direccion integer NOT NULL,
    calle character varying(30) COLLATE pg_catalog."default",
    id_parroquias integer,
    id_municipios integer,
    id_estados integer,
    cog_postal integer,
    CONSTRAINT direccion_pkey PRIMARY KEY (id_direccion)
);

CREATE TABLE IF NOT EXISTS public.discapacidad
(
    id_discapacidad integer NOT NULL,
    discapacidad character varying(100) COLLATE pg_catalog."default",
    activo integer,
    CONSTRAINT discapacidad_pkey PRIMARY KEY (id_discapacidad)
);

CREATE TABLE IF NOT EXISTS public.discapacidad_estudiante
(
    id_discapacidad_estudiante integer NOT NULL,
    medical_id integer NOT NULL,
    alumno_id integer NOT NULL,
    discapacidad_id integer NOT NULL,
    observacion text COLLATE pg_catalog."default",
    activo integer,
    CONSTRAINT discapacidad_estudiante_pkey PRIMARY KEY (id_discapacidad_estudiante)
);

CREATE TABLE IF NOT EXISTS public.enfermedad_estudiante
(
    id_enfermedad_estudiante integer NOT NULL,
    medical_id integer NOT NULL,
    alumno_id integer NOT NULL,
    enfermedades_id integer NOT NULL,
    fecha_diagnostico date,
    diagnostico character varying(100) COLLATE pg_catalog."default",
    observacion text COLLATE pg_catalog."default",
    activo integer,
    CONSTRAINT enfermedad_estudiante_pkey PRIMARY KEY (id_enfermedad_estudiante)
);

CREATE TABLE IF NOT EXISTS public.enfermedades
(
    id_enfermedad_cronica integer NOT NULL,
    enfermedades character varying(100) COLLATE pg_catalog."default",
    observacion text COLLATE pg_catalog."default",
    activo integer,
    CONSTRAINT enfermedades_pkey PRIMARY KEY (id_enfermedad_cronica)
);

CREATE TABLE IF NOT EXISTS public.especialidades_estudio
(
    id integer NOT NULL,
    nivel_id integer NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default",
    orden integer,
    status integer,
    CONSTRAINT especialidades_estudio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estados
(
    id_estado integer NOT NULL,
    descripcion character varying(250) COLLATE pg_catalog."default",
    ciudad_id integer NOT NULL,
    CONSTRAINT estados_pkey PRIMARY KEY (id_estado)
);

CREATE TABLE IF NOT EXISTS public.evaluaciones_especificas
(
    id_evaluacion integer NOT NULL,
    alumno_id integer NOT NULL,
    proyecto_id integer NOT NULL,
    materia_id integer NOT NULL,
    indicador_id integer NOT NULL,
    momento smallint NOT NULL,
    valor smallint NOT NULL,
    estado integer DEFAULT 1,
    registrado_por integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT evaluaciones_especificas_pkey PRIMARY KEY (id_evaluacion),
    CONSTRAINT uq_evaluacion_unica UNIQUE (alumno_id, proyecto_id, materia_id, indicador_id, momento, estado)
);

CREATE TABLE IF NOT EXISTS public.grados
(
    id_grado bigint NOT NULL,
    grado integer NOT NULL,
    status integer NOT NULL,
    CONSTRAINT grados_pkey PRIMARY KEY (id_grado)
);

CREATE TABLE IF NOT EXISTS public.grupo_sanguineo
(
    id_grupo_sanguineo integer NOT NULL,
    grupo_sanguineo character varying(10) COLLATE pg_catalog."default",
    activo integer,
    CONSTRAINT grupo_sanguineo_pkey PRIMARY KEY (id_grupo_sanguineo)
);

CREATE TABLE IF NOT EXISTS public.indicadores
(
    id_indicador integer NOT NULL,
    materia_id integer NOT NULL,
    grado_id bigint NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    orden integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT indicadores_pkey PRIMARY KEY (id_indicador),
    CONSTRAINT uq_indicador_materia_grado_nombre UNIQUE (materia_id, grado_id, nombre)
);

CREATE TABLE IF NOT EXISTS public.informacion_medica
(
    medical_id integer NOT NULL,
    alumno_id integer NOT NULL,
    parentesco_id integer,
    grupo_sanguineo_id integer,
    tratamiento text COLLATE pg_catalog."default",
    restricciones text COLLATE pg_catalog."default",
    alergias text COLLATE pg_catalog."default",
    CONSTRAINT informacion_medica_pkey PRIMARY KEY (medical_id)
);

CREATE TABLE IF NOT EXISTS public.inscripcion
(
    inscripcion_id integer NOT NULL,
    alumno_id integer NOT NULL,
    turno_id integer NOT NULL,
    status integer NOT NULL,
    grado_id integer,
    seccion_id integer,
    periodo_id integer,
    profesor_id integer,
    CONSTRAINT inscripcion_pkey PRIMARY KEY (inscripcion_id)
);

CREATE TABLE IF NOT EXISTS public.materias
(
    id_materia integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT materias_pkey PRIMARY KEY (id_materia),
    CONSTRAINT materias_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.municipios
(
    id_municipios integer NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_estado integer NOT NULL,
    CONSTRAINT municipios_pkey PRIMARY KEY (id_municipios)
);

CREATE TABLE IF NOT EXISTS public.nacionalidades
(
    id_nacionalidades integer NOT NULL,
    codigo character(1) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT nacionalidades_pkey PRIMARY KEY (id_nacionalidades)
);

CREATE TABLE IF NOT EXISTS public.niveles_estudio
(
    id integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    orden integer NOT NULL,
    status integer NOT NULL,
    CONSTRAINT modulos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notas_definitivas
(
    id_nota_definitiva integer NOT NULL,
    alumno_id integer NOT NULL,
    proyecto_id integer NOT NULL,
    materia_id integer NOT NULL,
    momento smallint NOT NULL,
    valor character(1) COLLATE pg_catalog."default" NOT NULL,
    origen smallint DEFAULT 1,
    estado integer DEFAULT 1,
    registrado_por integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notas_definitivas_pkey PRIMARY KEY (id_nota_definitiva),
    CONSTRAINT uq_nota_definitiva_unica UNIQUE (alumno_id, proyecto_id, materia_id, momento, estado)
);

CREATE TABLE IF NOT EXISTS public.observaciones
(
    observacion_id integer NOT NULL,
    alumno_id integer NOT NULL,
    representantes_id integer NOT NULL,
    profesor_id integer NOT NULL,
    tipo_observacion character varying(50) COLLATE pg_catalog."default",
    observacion text COLLATE pg_catalog."default",
    fecha_creacion timestamp with time zone,
    estatus integer,
    CONSTRAINT observaciones_pkey PRIMARY KEY (observacion_id)
);

CREATE TABLE IF NOT EXISTS public.parentescos
(
    id_parentesco integer NOT NULL,
    parentesco integer NOT NULL,
    activo integer NOT NULL,
    CONSTRAINT parentescos_pkey PRIMARY KEY (id_parentesco)
);

CREATE TABLE IF NOT EXISTS public.parroquias
(
    id_parroquias integer NOT NULL,
    municipios_id integer,
    descripcion character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT parroquias_pkey PRIMARY KEY (id_parroquias)
);

CREATE TABLE IF NOT EXISTS public.periodo_escolar
(
    periodo_id integer NOT NULL,
    anio_inicio integer,
    anio_fin integer,
    estatus integer,
    CONSTRAINT periodo_escolar_pkey PRIMARY KEY (periodo_id)
);

CREATE TABLE IF NOT EXISTS public.personas
(
    id_persona integer NOT NULL,
    id_nacionalidades integer NOT NULL,
    id_direccion integer NOT NULL,
    cedula integer NOT NULL,
    nombres character varying(20) COLLATE pg_catalog."default",
    apellidos character varying(20) COLLATE pg_catalog."default",
    sexo character(1) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date NOT NULL,
    correo_electronico character varying(30) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default",
    alumnos_id integer NOT NULL,
    profesores_id integer NOT NULL,
    representantes_id integer NOT NULL,
    CONSTRAINT personas_pkey PRIMARY KEY (id_persona),
    CONSTRAINT personas_cedula_unique UNIQUE (cedula)
);

CREATE TABLE IF NOT EXISTS public.profesores
(
    profesor_id integer NOT NULL,
    turno_id integer NOT NULL,
    status integer NOT NULL,
    es_director smallint NOT NULL,
    director_fecha_inicio date,
    director_fecha_fin date,
    CONSTRAINT profesores_pkey PRIMARY KEY (profesor_id)
);

CREATE TABLE IF NOT EXISTS public.profesores_niveles_estudio
(
    id integer NOT NULL,
    profesor_id integer NOT NULL,
    especializacion_id smallint NOT NULL,
    CONSTRAINT profesores_niveles_estudio_pkey PRIMARY KEY (profesor_id, especializacion_id)
);

CREATE TABLE IF NOT EXISTS public.proyecto_materias
(
    id_proyecto_materia serial NOT NULL,
    proyecto_id integer NOT NULL,
    materia_id integer NOT NULL,
    nivel_enfasis smallint DEFAULT 2,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT proyecto_materias_pkey PRIMARY KEY (id_proyecto_materia),
    CONSTRAINT uq_proyecto_materia UNIQUE (proyecto_id, materia_id)
);

CREATE TABLE IF NOT EXISTS public.proyectos
(
    id_proyecto integer NOT NULL,
    titulo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    grado_id bigint NOT NULL,
    seccion_id bigint NOT NULL,
    profesor_id integer NOT NULL,
    periodo_id integer NOT NULL,
    momento smallint NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    proposito text COLLATE pg_catalog."default" NOT NULL,
    contenidos text COLLATE pg_catalog."default" NOT NULL,
    actividades_integradoras text COLLATE pg_catalog."default" NOT NULL,
    aprendizajes_esperados text COLLATE pg_catalog."default" NOT NULL,
    tecnicas_evaluacion text COLLATE pg_catalog."default" NOT NULL,
    instrumentos_evaluacion text COLLATE pg_catalog."default" NOT NULL,
    actividades_impacto text COLLATE pg_catalog."default",
    participantes text COLLATE pg_catalog."default",
    recursos text COLLATE pg_catalog."default",
    estado integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT proyectos_pkey PRIMARY KEY (id_proyecto),
    CONSTRAINT uq_proyecto_grado_seccion_momento_periodo UNIQUE (grado_id, seccion_id, momento, periodo_id, estado)
);

CREATE TABLE IF NOT EXISTS public.representantes
(
    id_representates integer NOT NULL,
    estatus integer NOT NULL,
    CONSTRAINT representantes_pkey PRIMARY KEY (id_representates)
);

CREATE TABLE IF NOT EXISTS public.rol
(
    id integer NOT NULL,
    nombre_rol character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT rol_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.secciones
(
    id_seccion bigint NOT NULL,
    seccion character varying(5) COLLATE pg_catalog."default" NOT NULL,
    estatus integer NOT NULL,
    CONSTRAINT secciones_pkey PRIMARY KEY (id_seccion)
);

CREATE TABLE IF NOT EXISTS public.turno
(
    turno_id integer NOT NULL,
    tipo_turno character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT turno_pkey PRIMARY KEY (turno_id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario integer NOT NULL,
    id_rol integer NOT NULL,
    id_cedula integer NOT NULL,
    usuario character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    fecha_crecion timestamp with time zone,
    estatus integer,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuarios_id_cedula_unique UNIQUE (id_cedula)
);

CREATE TABLE IF NOT EXISTS public.vacuna_infantil
(
    id_vacuna_infantil integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    activo integer,
    CONSTRAINT vacuna_infantil_pkey PRIMARY KEY (id_vacuna_infantil)
);

ALTER TABLE IF EXISTS public.alumno_representante
    ADD CONSTRAINT fk_alumno_representante_parentescos FOREIGN KEY (parentesco_id)
    REFERENCES public.parentescos (id_parentesco) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS uq_alumno_representante_parentesco
    ON public.alumno_representante(parentesco_id);


ALTER TABLE IF EXISTS public.alumno_representante
    ADD CONSTRAINT fk_alumno_representante_representantes FOREIGN KEY (representantes_id)
    REFERENCES public.representantes (id_representates) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.alumno_vacuna
    ADD CONSTRAINT fk_alumvac_medical FOREIGN KEY (medical_id)
    REFERENCES public.informacion_medica (medical_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alumno_vacuna
    ADD CONSTRAINT fk_alumvac_vacuna FOREIGN KEY (vacuna_id)
    REFERENCES public.vacuna_infantil (id_vacuna_infantil) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alumnos
    ADD CONSTRAINT fk_alumnos_personas FOREIGN KEY (id_alumnos)
    REFERENCES public.personas (id_persona) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS alumnos_pkey
    ON public.alumnos(id_alumnos);


ALTER TABLE IF EXISTS public.alumnos_atencion_medica
    ADD CONSTRAINT fk_atencion_medical FOREIGN KEY (medical_id)
    REFERENCES public.informacion_medica (medical_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.auditoria_notas
    ADD CONSTRAINT auditoria_notas_alumno_id_fkey FOREIGN KEY (alumno_id)
    REFERENCES public.alumnos (id_alumnos) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_auditoria_alumno_id
    ON public.auditoria_notas(alumno_id);


ALTER TABLE IF EXISTS public.auditoria_notas
    ADD CONSTRAINT auditoria_notas_materia_id_fkey FOREIGN KEY (materia_id)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_auditoria_materia_id
    ON public.auditoria_notas(materia_id);


ALTER TABLE IF EXISTS public.auditoria_notas
    ADD CONSTRAINT auditoria_notas_proyecto_id_fkey FOREIGN KEY (proyecto_id)
    REFERENCES public.proyectos (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_auditoria_proyecto_id
    ON public.auditoria_notas(proyecto_id);


ALTER TABLE IF EXISTS public.auditoria_notas
    ADD CONSTRAINT auditoria_notas_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario_id
    ON public.auditoria_notas(usuario_id);


ALTER TABLE IF EXISTS public.boletines_generados
    ADD CONSTRAINT boletines_generados_alumno_id_fkey FOREIGN KEY (alumno_id)
    REFERENCES public.alumnos (id_alumnos) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_boletines_alumno_id
    ON public.boletines_generados(alumno_id);


ALTER TABLE IF EXISTS public.boletines_generados
    ADD CONSTRAINT boletines_generados_generado_por_fkey FOREIGN KEY (generado_por)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_boletines_generado_por
    ON public.boletines_generados(generado_por);


ALTER TABLE IF EXISTS public.boletines_generados
    ADD CONSTRAINT boletines_generados_grado_id_fkey FOREIGN KEY (grado_id)
    REFERENCES public.grados (id_grado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_boletines_grado_id
    ON public.boletines_generados(grado_id);


ALTER TABLE IF EXISTS public.boletines_generados
    ADD CONSTRAINT boletines_generados_periodo_id_fkey FOREIGN KEY (periodo_id)
    REFERENCES public.periodo_escolar (periodo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_boletines_periodo_id
    ON public.boletines_generados(periodo_id);


ALTER TABLE IF EXISTS public.boletines_generados
    ADD CONSTRAINT boletines_generados_proyecto_id_fkey FOREIGN KEY (proyecto_id)
    REFERENCES public.proyectos (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.boletines_generados
    ADD CONSTRAINT boletines_generados_seccion_id_fkey FOREIGN KEY (seccion_id)
    REFERENCES public.secciones (id_seccion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_boletines_seccion_id
    ON public.boletines_generados(seccion_id);


ALTER TABLE IF EXISTS public.cierres_momentos
    ADD CONSTRAINT cierres_momentos_cerrado_por_fkey FOREIGN KEY (cerrado_por)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_cierres_cerrado_por
    ON public.cierres_momentos(cerrado_por);


ALTER TABLE IF EXISTS public.cierres_momentos
    ADD CONSTRAINT cierres_momentos_grado_id_fkey FOREIGN KEY (grado_id)
    REFERENCES public.grados (id_grado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_cierres_grado_id
    ON public.cierres_momentos(grado_id);


ALTER TABLE IF EXISTS public.cierres_momentos
    ADD CONSTRAINT cierres_momentos_periodo_id_fkey FOREIGN KEY (periodo_id)
    REFERENCES public.periodo_escolar (periodo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_cierres_periodo_id
    ON public.cierres_momentos(periodo_id);


ALTER TABLE IF EXISTS public.cierres_momentos
    ADD CONSTRAINT cierres_momentos_seccion_id_fkey FOREIGN KEY (seccion_id)
    REFERENCES public.secciones (id_seccion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_cierres_seccion_id
    ON public.cierres_momentos(seccion_id);


ALTER TABLE IF EXISTS public.ciudad
    ADD CONSTRAINT fk_ciudad_estado FOREIGN KEY (estado_id)
    REFERENCES public.estados (id_estado) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.configuracion_regla_calculo
    ADD CONSTRAINT configuracion_regla_calculo_materia_id_fkey FOREIGN KEY (materia_id)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_regla_materia_id
    ON public.configuracion_regla_calculo(materia_id);


ALTER TABLE IF EXISTS public.contacto_emergencia
    ADD CONSTRAINT fk_contacto_parentesco FOREIGN KEY (parentesco_id)
    REFERENCES public.parentescos (id_parentesco) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.direccion
    ADD CONSTRAINT fk_direccion_estados FOREIGN KEY (id_estados)
    REFERENCES public.estados (id_estado) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.direccion
    ADD CONSTRAINT fk_direccion_municipios FOREIGN KEY (id_municipios)
    REFERENCES public.municipios (id_municipios) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.direccion
    ADD CONSTRAINT fk_direccion_parroquias FOREIGN KEY (id_parroquias)
    REFERENCES public.parroquias (id_parroquias) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.discapacidad_estudiante
    ADD CONSTRAINT fk_discapest_discapacidad FOREIGN KEY (discapacidad_id)
    REFERENCES public.discapacidad (id_discapacidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.discapacidad_estudiante
    ADD CONSTRAINT fk_discapest_medical FOREIGN KEY (medical_id)
    REFERENCES public.informacion_medica (medical_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enfermedad_estudiante
    ADD CONSTRAINT fk_enfermest_enfermedad FOREIGN KEY (enfermedades_id)
    REFERENCES public.enfermedades (id_enfermedad_cronica) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enfermedad_estudiante
    ADD CONSTRAINT fk_enfermest_medical FOREIGN KEY (medical_id)
    REFERENCES public.informacion_medica (medical_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.especialidades_estudio
    ADD CONSTRAINT fk_especialidades_estudio_nivel FOREIGN KEY (nivel_id)
    REFERENCES public.niveles_estudio (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.estados
    ADD CONSTRAINT fk_estados_ciudad FOREIGN KEY (ciudad_id)
    REFERENCES public.ciudad (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.evaluaciones_especificas
    ADD CONSTRAINT evaluaciones_especificas_alumno_id_fkey FOREIGN KEY (alumno_id)
    REFERENCES public.alumnos (id_alumnos) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eval_especificas_alumno_id
    ON public.evaluaciones_especificas(alumno_id);


ALTER TABLE IF EXISTS public.evaluaciones_especificas
    ADD CONSTRAINT evaluaciones_especificas_indicador_id_fkey FOREIGN KEY (indicador_id)
    REFERENCES public.indicadores (id_indicador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eval_especificas_indicador_id
    ON public.evaluaciones_especificas(indicador_id);


ALTER TABLE IF EXISTS public.evaluaciones_especificas
    ADD CONSTRAINT evaluaciones_especificas_materia_id_fkey FOREIGN KEY (materia_id)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eval_especificas_materia_id
    ON public.evaluaciones_especificas(materia_id);


ALTER TABLE IF EXISTS public.evaluaciones_especificas
    ADD CONSTRAINT evaluaciones_especificas_proyecto_id_fkey FOREIGN KEY (proyecto_id)
    REFERENCES public.proyectos (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eval_especificas_proyecto_id
    ON public.evaluaciones_especificas(proyecto_id);


ALTER TABLE IF EXISTS public.evaluaciones_especificas
    ADD CONSTRAINT evaluaciones_especificas_registrado_por_fkey FOREIGN KEY (registrado_por)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eval_especificas_registrado_por
    ON public.evaluaciones_especificas(registrado_por);


ALTER TABLE IF EXISTS public.indicadores
    ADD CONSTRAINT indicadores_grado_id_fkey FOREIGN KEY (grado_id)
    REFERENCES public.grados (id_grado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_indicadores_grado_id
    ON public.indicadores(grado_id);


ALTER TABLE IF EXISTS public.indicadores
    ADD CONSTRAINT indicadores_materia_id_fkey FOREIGN KEY (materia_id)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_indicadores_materia_id
    ON public.indicadores(materia_id);


ALTER TABLE IF EXISTS public.informacion_medica
    ADD CONSTRAINT fk_infomedica_gruposanguineo FOREIGN KEY (grupo_sanguineo_id)
    REFERENCES public.grupo_sanguineo (id_grupo_sanguineo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.informacion_medica
    ADD CONSTRAINT fk_infomedica_parentesco FOREIGN KEY (parentesco_id)
    REFERENCES public.parentescos (id_parentesco) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripcion
    ADD CONSTRAINT fk_inscripcion_alumno FOREIGN KEY (alumno_id)
    REFERENCES public.alumnos (id_alumnos) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.inscripcion
    ADD CONSTRAINT fk_inscripcion_grado FOREIGN KEY (grado_id)
    REFERENCES public.grados (id_grado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripcion
    ADD CONSTRAINT fk_inscripcion_periodo FOREIGN KEY (periodo_id)
    REFERENCES public.periodo_escolar (periodo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripcion
    ADD CONSTRAINT fk_inscripcion_profesor FOREIGN KEY (profesor_id)
    REFERENCES public.profesores (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripcion
    ADD CONSTRAINT fk_inscripcion_seccion FOREIGN KEY (seccion_id)
    REFERENCES public.secciones (id_seccion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripcion
    ADD CONSTRAINT fk_inscripcion_turno FOREIGN KEY (turno_id)
    REFERENCES public.turno (turno_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.municipios
    ADD CONSTRAINT fk_municipios_estado FOREIGN KEY (id_estado)
    REFERENCES public.estados (id_estado) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notas_definitivas
    ADD CONSTRAINT notas_definitivas_alumno_id_fkey FOREIGN KEY (alumno_id)
    REFERENCES public.alumnos (id_alumnos) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_notas_definitivas_alumno_id
    ON public.notas_definitivas(alumno_id);


ALTER TABLE IF EXISTS public.notas_definitivas
    ADD CONSTRAINT notas_definitivas_materia_id_fkey FOREIGN KEY (materia_id)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_notas_definitivas_materia_id
    ON public.notas_definitivas(materia_id);


ALTER TABLE IF EXISTS public.notas_definitivas
    ADD CONSTRAINT notas_definitivas_proyecto_id_fkey FOREIGN KEY (proyecto_id)
    REFERENCES public.proyectos (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_notas_definitivas_proyecto_id
    ON public.notas_definitivas(proyecto_id);


ALTER TABLE IF EXISTS public.notas_definitivas
    ADD CONSTRAINT notas_definitivas_registrado_por_fkey FOREIGN KEY (registrado_por)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_notas_definitivas_registrado_por
    ON public.notas_definitivas(registrado_por);


ALTER TABLE IF EXISTS public.observaciones
    ADD CONSTRAINT fk_observaciones_profesores FOREIGN KEY (profesor_id)
    REFERENCES public.profesores (profesor_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.parroquias
    ADD CONSTRAINT fk_parroquias_municipios FOREIGN KEY (municipios_id)
    REFERENCES public.municipios (id_municipios) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.personas
    ADD CONSTRAINT fk_personas_alumnos FOREIGN KEY (alumnos_id)
    REFERENCES public.alumnos (id_alumnos) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.personas
    ADD CONSTRAINT fk_personas_direccion FOREIGN KEY (id_direccion)
    REFERENCES public.direccion (id_direccion) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.personas
    ADD CONSTRAINT fk_personas_nacionalidades FOREIGN KEY (id_nacionalidades)
    REFERENCES public.nacionalidades (id_nacionalidades) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.personas
    ADD CONSTRAINT fk_personas_profesores FOREIGN KEY (profesores_id)
    REFERENCES public.profesores (profesor_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.personas
    ADD CONSTRAINT fk_personas_representantes FOREIGN KEY (representantes_id)
    REFERENCES public.representantes (id_representates) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.personas
    ADD CONSTRAINT fk_personas_usuarios FOREIGN KEY (cedula)
    REFERENCES public.usuarios (id_cedula) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS personas_cedula_unique
    ON public.personas(cedula);


ALTER TABLE IF EXISTS public.profesores
    ADD CONSTRAINT fk_profesores_personas FOREIGN KEY (profesor_id)
    REFERENCES public.personas (id_persona) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS profesores_pkey
    ON public.profesores(profesor_id);


ALTER TABLE IF EXISTS public.profesores_niveles_estudio
    ADD CONSTRAINT fk_profesores_niveles_estudio_especialidad FOREIGN KEY (especializacion_id)
    REFERENCES public.especialidades_estudio (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.profesores_niveles_estudio
    ADD CONSTRAINT fk_profesores_niveles_estudio_profesor FOREIGN KEY (profesor_id)
    REFERENCES public.profesores (profesor_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.proyecto_materias
    ADD CONSTRAINT proyecto_materias_materia_id_fkey FOREIGN KEY (materia_id)
    REFERENCES public.materias (id_materia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_proyecto_materias_materia_id
    ON public.proyecto_materias(materia_id);


ALTER TABLE IF EXISTS public.proyecto_materias
    ADD CONSTRAINT proyecto_materias_proyecto_id_fkey FOREIGN KEY (proyecto_id)
    REFERENCES public.proyectos (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_proyecto_materias_proyecto_id
    ON public.proyecto_materias(proyecto_id);


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_grado_id_fkey FOREIGN KEY (grado_id)
    REFERENCES public.grados (id_grado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_proyectos_grado_id
    ON public.proyectos(grado_id);


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_periodo_id_fkey FOREIGN KEY (periodo_id)
    REFERENCES public.periodo_escolar (periodo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_proyectos_periodo_id
    ON public.proyectos(periodo_id);


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_profesor_id_fkey FOREIGN KEY (profesor_id)
    REFERENCES public.profesores (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_proyectos_profesor_id
    ON public.proyectos(profesor_id);


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_seccion_id_fkey FOREIGN KEY (seccion_id)
    REFERENCES public.secciones (id_seccion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_proyectos_seccion_id
    ON public.proyectos(seccion_id);


ALTER TABLE IF EXISTS public.representantes
    ADD CONSTRAINT fk_representantes_personas FOREIGN KEY (id_representates)
    REFERENCES public.personas (id_persona) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS representantes_pkey
    ON public.representantes(id_representates);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT fk_usuarios_rol FOREIGN KEY (id_rol)
    REFERENCES public.rol (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

END;