<?php
// Disable error reporting to prevent JSON corruption
error_reporting(0);
ini_set('display_errors', 0);

// Start output buffering to catch any prior output
ob_start();

try {
    require_once '../../includes/config.php';
} catch (Exception $e) {
    // Si hay error en config, capturarlo sin generar output
    ob_clean();
    header('Content-Type: application/json; charset=UTF-8');
    echo json_encode(array('status' => false, 'msg' => 'Error de configuración del sistema'), JSON_UNESCAPED_UNICODE);
    ob_end_flush();
    die();
}

// Discard any output generated by includes (whitespace, warnings, errors)
$output = ob_get_contents();
ob_clean();

// Si hubo output no deseado, manejarlo
if (!empty($output) && trim($output) !== '') {
    // Si el output es un error de conexión, manejarlo
    if (strpos($output, 'ERROR:') !== false) {
        header('Content-Type: application/json; charset=UTF-8');
        echo json_encode(array('status' => false, 'msg' => 'Error de conexión a la base de datos'), JSON_UNESCAPED_UNICODE);
        ob_end_flush();
        die();
    }
    // Si hay otro tipo de output, limpiarlo y continuar
}

header('Content-Type: application/json; charset=UTF-8');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['idProfesor']) && !empty($_POST['idProfesor'])) {
        $idProfesor = intval($_POST['idProfesor']);
        $motivo = isset($_POST['motivo']) ? trim($_POST['motivo']) : '';

        if (empty($motivo)) {
            $arrResponse = array('status' => false, 'msg' => 'El motivo de activación es obligatorio');
            echo json_encode($arrResponse, JSON_UNESCAPED_UNICODE);
            ob_end_flush();
            die();
        }

        try {
            // Insertar en observaciones
            // La tabla observaciones no tiene columna usuario_nombre según la estructura SQL
            $observacionContent = "Reactivación de Profesor. Motivo: " . $motivo;
            
            $sqlObs = "INSERT INTO observaciones (profesor_id, tipo_observacion, observacion, estatus) VALUES (?, 'reactivacion', ?, 1)";
            $queryObs = $pdo->prepare($sqlObs);
            $queryObs->execute([$idProfesor, $observacionContent]);

            // Activar Profesor
            $sql = "UPDATE profesor SET estatus = 1 WHERE profesor_id = ?";
            $query = $pdo->prepare($sql);
            $result = $query->execute([$idProfesor]);

            if ($result && $query->rowCount() > 0) {
                $arrResponse = array('status' => true, 'msg' => 'Profesor activado correctamente');
            } else {
                $arrResponse = array('status' => false, 'msg' => 'No se pudo activar el profesor o ya está activo');
            }
        } catch (PDOException $e) {
            $arrResponse = array('status' => false, 'msg' => 'Error en la base de datos: ' . $e->getMessage());
        } catch (Exception $e) {
            $arrResponse = array('status' => false, 'msg' => 'Error del sistema: ' . $e->getMessage());
        }
    } else {
        $arrResponse = array('status' => false, 'msg' => 'Error de datos');
    }
    echo json_encode($arrResponse, JSON_UNESCAPED_UNICODE);
    ob_end_flush();
} else {
    echo json_encode(array('status' => false, 'msg' => 'Método no permitido'), JSON_UNESCAPED_UNICODE);
    ob_end_flush();
}
