<?php
// Disable error reporting to prevent JSON corruption
error_reporting(0);
ini_set('display_errors', 0);

// Start output buffering to catch any prior output
ob_start();

try {
    require_once '../../includes/config.php';
} catch (Exception $e) {
    // Si hay error en config, capturarlo sin generar output
    ob_clean();
    header('Content-Type: application/json; charset=UTF-8');
    echo json_encode(array('status' => false, 'msg' => 'Error de configuración del sistema'), JSON_UNESCAPED_UNICODE);
    ob_end_flush();
    die();
}

// Discard any output generated by includes (whitespace, warnings, errors)
$output = ob_get_contents();
ob_clean();

// Si hubo output no deseado, loguearlo pero continuar
if (!empty($output) && trim($output) !== '') {
    // Si el output es un error de conexión, manejarlo
    if (strpos($output, 'ERROR:') !== false) {
        header('Content-Type: application/json; charset=UTF-8');
        echo json_encode(array('status' => false, 'msg' => 'Error de conexión a la base de datos'), JSON_UNESCAPED_UNICODE);
        ob_end_flush();
        die();
    }
    // Si hay otro tipo de output, limpiarlo y continuar
}

header('Content-Type: application/json; charset=UTF-8');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Validar que el parámetro idProfesor exista y no esté vacío
    // Validar que el parámetro idProfesor exista y no esté vacío
    if (isset($_POST['idProfesor']) && !empty($_POST['idProfesor'])) {
        $idProfesor = intval($_POST['idProfesor']); 
        $motivo = isset($_POST['motivo']) ? trim($_POST['motivo']) : '';

        if (empty($motivo)) {
            $arrResponse = array('status' => false, 'msg' => 'El motivo es obligatorio');
            echo json_encode($arrResponse, JSON_UNESCAPED_UNICODE);
            ob_end_flush();
            die();
        }

        try {
            // 1. Obtener periodo activo global
            $sqlPeriodo = "SELECT periodo_id, anio_inicio, anio_fin FROM periodo_escolar WHERE estatus = 1 LIMIT 1";
            $queryPeriodo = $pdo->query($sqlPeriodo);
            $periodoActivo = $queryPeriodo->fetch(PDO::FETCH_ASSOC);
            $idPeriodoActivo = $periodoActivo ? $periodoActivo['periodo_id'] : 0;

            // 2. Obtener historial de cursos (todos los tiempos) para guardar en observación
            $sqlHistory = "SELECT 
                                g.grado, 
                                s.seccion, 
                                pe.anio_inicio, 
                                pe.anio_fin 
                           FROM curso c
                           INNER JOIN grados g ON c.grados_id = g.id_grado
                           INNER JOIN seccion s ON c.seccion_id = s.id_seccion
                           INNER JOIN periodo_escolar pe ON c.periodo_id = pe.periodo_id
                           WHERE c.profesor_id = ?";
            $queryHistory = $pdo->prepare($sqlHistory);
            $queryHistory->execute([$idProfesor]);
            $historialCursos = $queryHistory->fetchAll(PDO::FETCH_ASSOC);

            $historyString = "Inhabilitación de Profesor. ";
            if (!empty($historialCursos)) {
                $historyString .= "Historial de Grados/Secciones: ";
                $cursosStr = [];
                foreach ($historialCursos as $curso) {
                    // Formato: 1° - A (2023-2024)
                    $cursosStr[] = "{$curso['grado']}° - {$curso['seccion']} ({$curso['anio_inicio']}-{$curso['anio_fin']})";
                }
                $historyString .= implode(', ', $cursosStr);
            } else {
                $historyString .= "No tenía cursos asignados.";
            }

            // Añadir el motivo del usuario
            $observacionFinal = $historyString . ". Motivo: " . $motivo;

            // 3. Insertar en observaciones
            // La tabla observaciones no tiene columna usuario_nombre según la estructura SQL
            $sqlObs = "INSERT INTO observaciones (profesor_id, tipo_observacion, observacion, estatus) VALUES (?, 'inhabilitacion', ?, 1)";
            $queryObs = $pdo->prepare($sqlObs);
            $queryObs->execute([$idProfesor, $observacionFinal]);

            // 4. Inhabilitar Profesor (Global)
            $sql = "UPDATE profesor SET estatus = 2 WHERE profesor_id = ?";
            $query = $pdo->prepare($sql);
            $result = $query->execute([$idProfesor]);

            if ($result && $query->rowCount() > 0) {
                $mensaje = 'Profesor inhabilitado y observación registrada.';
                
                // 5. Desvincular cursos SOLO del periodo activo
                // SE COMENTA POR PETICION: No desvincular para mantener el registro visual de quien daba la clase.
                /*
                if ($idPeriodoActivo > 0) {
                    // NO borrar el curso, SOLO quitar el profesor (profesor_id = 0 o NULL) enviando a "Por asignar"
                    $sqlUnlink = "UPDATE curso SET profesor_id = 0 WHERE profesor_id = ? AND periodo_id = ?";
                    $queryUnlink = $pdo->prepare($sqlUnlink);
                    $queryUnlink->execute([$idProfesor, $idPeriodoActivo]);
                    
                    $cursosDesvinculados = $queryUnlink->rowCount();
                    if ($cursosDesvinculados > 0) {
                        $mensaje .= " Se desvincularon $cursosDesvinculados curso(s) del periodo actual.";
                    }
                }
                */
                
                $arrResponse = array('status' => true, 'msg' => $mensaje);
            } else {
                $arrResponse = array('status' => false, 'msg' => 'No se pudo inhabilitar al profesor (posiblemente ya estaba inactivo).');
            }
        } catch (PDOException $e) {
            $arrResponse = array('status' => false, 'msg' => 'Error en la base de datos: ' . $e->getMessage());
        } catch (Exception $e) {
            $arrResponse = array('status' => false, 'msg' => 'Error del sistema: ' . $e->getMessage());
        }
    } else {
        $arrResponse = array('status' => false, 'msg' => 'Parámetro idProfesor faltante');
    }

    echo json_encode($arrResponse, JSON_UNESCAPED_UNICODE);
    ob_end_flush();
} else {
    echo json_encode(array('status' => false, 'msg' => 'Método no permitido'), JSON_UNESCAPED_UNICODE);
    ob_end_flush();
}