<?php
// Disable error reporting to prevent JSON corruption
error_reporting(0);
ini_set('display_errors', 0);

// Start output buffering to catch any prior output
ob_start();

require_once '../../includes/config.php';

// Discard any output generated by includes (whitespace, warnings)
ob_clean();

try {
    // Actualizar estados de directores vencidos globalmente
    $fechaActual = date('Y-m-d');
    $sqlUpdateStatus = "UPDATE profesores SET es_director = 2 WHERE es_director = 1 AND director_fecha_fin IS NOT NULL AND director_fecha_fin < ?";
    $queryUpdate = $pdo->prepare($sqlUpdateStatus);
    $queryUpdate->execute([$fechaActual]);
} catch (Exception $e) {
    // Continue silently
}

try {
    // Consulta SQL optimizada
    $sql = "SELECT 
                pr.profesor_id,
                p.cedula,
                p.nombres AS nombre,
                p.apellidos AS apellido,
                p.sexo,
                p.id_estado,
                p.id_ciudad,
                p.id_municipio,
                p.id_parroquia,
                p.telefono,
                p.correo_electronico AS correo,
                pr.es_director,
                pr.status AS estatus,
                pr.director_fecha_inicio,
                pr.director_fecha_fin,
                e.estado as nombre_estado,
                c.ciudad as nombre_ciudad,
                m.municipio as nombre_municipio,
                pa.parroquia as nombre_parroquia
            FROM profesores pr
            LEFT JOIN personas p ON p.profesores_id = pr.profesor_id
            LEFT JOIN estados e ON p.id_estado = e.id_estado
            LEFT JOIN ciudades c ON p.id_ciudad = c.id_ciudad
            LEFT JOIN municipios m ON p.id_municipio = m.id_municipio
            LEFT JOIN parroquias pa ON p.id_parroquia = pa.id_parroquia
            WHERE pr.status != 0";
    $data = $query->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    file_put_contents('debug_profesores_error.txt', $e->getMessage());
    $data = [];
}

// Function to force UTF-8 recursively
function utf8ize($d) {
    if (is_array($d)) {
        foreach ($d as $k => $v) {
            $d[$k] = utf8ize($v);
        }
    } else if (is_string($d)) {
        return mb_convert_encoding($d, 'UTF-8', 'UTF-8');
    }
    return $d;
}

$data = utf8ize($data);

// Process Data for Datatables
for ($i = 0; $i < count($data); $i++) {
    // Ensure keys
    $data[$i]['profesor_id'] = $data[$i]['profesor_id'] ?? 0;
    $data[$i]['estatus'] = $data[$i]['estatus'] ?? 0;
    $data[$i]['es_director'] = $data[$i]['es_director'] ?? 0;

    // Status Badges
    $estatusBadges = '';
    if ($data[$i]['estatus'] == 1) {
        $estatusBadges = '<span class="badge badge-success">Activo</span>';
    } else {
        $estatusBadges = '<span class="badge badge-danger">Inactivo</span>';
    }

    $isActiveDirector = 0;
    if ($data[$i]['es_director'] == 1) {
        $estatusBadges .= ' <span class="badge badge-info">Director</span>';
        $isActiveDirector = 1;
    } elseif ($data[$i]['es_director'] == 2) {
        $estatusBadges .= ' <span class="badge badge-secondary">Ex-Director</span>';
        $isActiveDirector = 2;
    }
    $data[$i]['estatus'] = $estatusBadges;

    // Address
    $parts = [];
    if (!empty($data[$i]['nombre_parroquia'])) $parts[] = $data[$i]['nombre_parroquia'];
    if (!empty($data[$i]['nombre_municipio'])) $parts[] = $data[$i]['nombre_municipio'];
    if (!empty($data[$i]['nombre_ciudad'])) $parts[] = $data[$i]['nombre_ciudad'];
    if (!empty($data[$i]['nombre_estado'])) $parts[] = $data[$i]['nombre_estado'];
    
    $fullAddr = '';
    if (!empty($parts)) {
        $fullAddr .= implode(', ', $parts);
    }
    $data[$i]['direccion'] = $fullAddr;

    // Phone
    if (!empty($data[$i]['telefono']) && strlen($data[$i]['telefono']) == 11) {
        $data[$i]['telefono'] = substr($data[$i]['telefono'], 0, 4) . '-' . substr($data[$i]['telefono'], 4);
    }

    // Obtener Niveles de Educación y Especialidades
    try {
        $sqlNiveles = "SELECT ee.nombre as nivel_estudio, ne.nombre as categoria 
                       FROM profesor_niveles_estudio pne
                       JOIN especialidades_estudio ee ON pne.especializacion_id = ee.id
                       JOIN niveles_estudio ne ON ee.nivel_id = ne.id
                       WHERE pne.profesor_id = ?
                       ORDER BY ne.nombre, ee.nombre";
                       
        $qNiv = $pdo->prepare($sqlNiveles);
        $qNiv->execute([$data[$i]['profesor_id']]);
        $niveles = $qNiv->fetchAll(PDO::FETCH_ASSOC);
        
        $nivelesHtml = '';
        if ($niveles) {
            foreach ($niveles as $n) {
                $cat = $n['categoria'];
                $esp = $n['nivel_estudio'];
                $txt = "<b>$cat</b>" . ($esp != '__DEFAULT__' ? " - $esp" : "");
                $nivelesHtml .= '<span class="d-block mb-1" style="white-space: normal;">' . $txt . '</span>';
            }
        }
        $data[$i]['nivel_est'] = $nivelesHtml ?: '<span class="text-muted">No especificado</span>';
    } catch (Exception $ex) {
        $data[$i]['nivel_est'] = '<span class="text-danger">Error: ' . $ex->getMessage() . '</span>';
    }

    // Options
    $btnEdit = '<button class="btn btn-dark btn-sm btnEditProfesor" rl="' . $data[$i]['profesor_id'] . '" title="Editar"><i class="fas fa-pencil-alt"></i></button>';
    $btnActivate = '<button class="btn btn-success btn-sm btnActivateProfesor" rl="' . $data[$i]['profesor_id'] . '" title="Activar"><i class="fas fa-check"></i></button>';
    $btnInactivate = '<button class="btn btn-danger btn-sm btnDelProfesor" rl="' . $data[$i]['profesor_id'] . '" is_director="' . $isActiveDirector . '" title="Inhabilitar"><i class="fas fa-ban" aria-hidden="true"></i></button>';

    if (strpos($data[$i]['estatus'], 'badge-success') !== false) {
        $data[$i]['options'] = '<div class="text-center">' . $btnEdit . ' ' . $btnInactivate . '</div>';
    } else {
        $btnEditDisabled = '<button class="btn btn-dark btn-sm btnEditProfesor" rl="' . $data[$i]['profesor_id'] . '" title="Editar" disabled><i class="fas fa-pencil-alt"></i></button>';
        $data[$i]['options'] = '<div class="text-center">' . $btnEditDisabled . ' ' . $btnActivate . '</div>';
    }
}

// Final JSON Output
$json = json_encode($data, JSON_UNESCAPED_UNICODE);

header('Content-Type: application/json; charset=utf-8');

if ($json === false) {
    // If JSON fails, write error to file and return empty array to prevent DataTable crash
    file_put_contents('debug_json_error.txt', json_last_error_msg());
    echo '[]'; 
} else {
    echo $json;
}
die();